use std::path::PathBuf;

use chrono::DateTime;
use chrono::Utc;
use codex_protocol::ThreadId;
use codex_protocol::config_types::ServiceTier;
use codex_protocol::dynamic_tools::DynamicToolSpec;
use codex_protocol::models::BaseInstructions;
use codex_protocol::openai_models::ReasoningEffort;
use codex_protocol::protocol::AskForApproval;
use codex_protocol::protocol::GitInfo;
use codex_protocol::protocol::RolloutItem;
use codex_protocol::protocol::SandboxPolicy;
use codex_protocol::protocol::SessionSource;
use codex_protocol::protocol::TokenUsage;
use serde::Deserialize;
use serde::Serialize;

/// Describes who owns a thread for multi-tenant storage backends.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct ThreadOwner {
    /// ChatGPT user identifier, when available from the active auth credentials.
    pub chatgpt_user_id: Option<String>,
    /// Workspace/account identifier, when available from the active auth credentials.
    pub account_id: Option<String>,
    /// Auth mode string captured for diagnostics and backend policy decisions.
    pub auth_mode: Option<String>,
}

/// Controls how many event variants should be persisted for future replay.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum ThreadEventPersistenceMode {
    /// Persist only the legacy minimal replay surface.
    #[default]
    Limited,
    /// Persist the richer event surface used by app-server history reconstruction.
    Extended,
}

/// Parameters required to create a persisted thread and its recorder.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CreateThreadParams {
    /// Thread id generated by Codex before opening persistence.
    pub thread_id: ThreadId,
    /// Tenant/owner metadata for multi-tenant stores.
    pub owner: ThreadOwner,
    /// Source thread id when this thread is created as a fork.
    pub forked_from_id: Option<ThreadId>,
    /// Runtime source for the thread.
    pub source: SessionSource,
    /// Working directory captured at thread start.
    pub cwd: PathBuf,
    /// Originator value captured in session metadata.
    pub originator: String,
    /// CLI/app version creating the thread.
    pub cli_version: String,
    /// Model provider id selected for the thread.
    pub model_provider: String,
    /// Optional model selected at thread start.
    pub model: Option<String>,
    /// Optional service tier selected at thread start.
    pub service_tier: Option<ServiceTier>,
    /// Optional reasoning effort selected at thread start.
    pub reasoning_effort: Option<ReasoningEffort>,
    /// Approval mode selected at thread start.
    pub approval_mode: AskForApproval,
    /// Sandbox policy selected at thread start.
    pub sandbox_policy: SandboxPolicy,
    /// Base instructions persisted in session metadata.
    pub base_instructions: BaseInstructions,
    /// Dynamic tools available to the thread at startup.
    pub dynamic_tools: Vec<DynamicToolSpec>,
    /// Optional initial memory mode, for example `disabled`.
    pub memory_mode: Option<String>,
    /// Optional git metadata captured by the caller.
    pub git_info: Option<GitInfo>,
    /// Whether the recorder should persist the extended event surface.
    pub event_persistence_mode: ThreadEventPersistenceMode,
}

/// Parameters required to reopen persistence for an existing thread.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ResumeThreadRecorderParams {
    /// Existing thread id whose future items should be appended.
    pub thread_id: ThreadId,
    /// Tenant/owner metadata for multi-tenant stores.
    pub owner: ThreadOwner,
    /// Whether archived threads may be reopened.
    pub include_archived: bool,
    /// Whether the recorder should persist the extended event surface.
    pub event_persistence_mode: ThreadEventPersistenceMode,
}

/// Parameters for appending rollout items outside a live recorder.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AppendThreadItemsParams {
    /// Thread id to append to.
    pub thread_id: ThreadId,
    /// Tenant/owner metadata for multi-tenant stores.
    pub owner: ThreadOwner,
    /// Items to append in order.
    pub items: Vec<RolloutItem>,
    /// Optional idempotency key supplied by callers that may retry the same append.
    pub idempotency_key: Option<String>,
    /// Optional timestamp override for the thread's updated-at value.
    pub updated_at: Option<DateTime<Utc>>,
    /// Optional memory mode update associated with this append.
    pub new_thread_memory_mode: Option<String>,
}

/// Parameters for loading persisted history for resume, fork, rollback, and memory jobs.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct LoadThreadHistoryParams {
    /// Thread id to load.
    pub thread_id: ThreadId,
    /// Tenant/owner metadata for multi-tenant stores.
    pub owner: ThreadOwner,
    /// Whether archived threads are eligible.
    pub include_archived: bool,
}

/// Persisted rollout history for a thread, without any filesystem path requirement.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StoredThreadHistory {
    /// Thread id represented by the history.
    pub thread_id: ThreadId,
    /// Persisted rollout items in replay order.
    pub items: Vec<RolloutItem>,
}

/// Parameters for reading a thread summary and optionally its replay history.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ReadThreadParams {
    /// Thread id to read.
    pub thread_id: ThreadId,
    /// Tenant/owner metadata for multi-tenant stores.
    pub owner: ThreadOwner,
    /// Whether archived threads are eligible.
    pub include_archived: bool,
    /// Whether persisted rollout items should be included in the response.
    pub include_history: bool,
}

/// The sort key to use when listing stored threads.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum ThreadSortKey {
    /// Sort by the thread creation timestamp.
    #[default]
    CreatedAt,
    /// Sort by the thread last-update timestamp.
    UpdatedAt,
}

/// Parameters for listing threads.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ListThreadsParams {
    /// Tenant/owner metadata for multi-tenant stores.
    pub owner: ThreadOwner,
    /// Maximum number of threads to return.
    pub page_size: usize,
    /// Opaque cursor returned by a previous list call.
    pub cursor: Option<String>,
    /// Sort order requested by the caller.
    pub sort_key: ThreadSortKey,
    /// Allowed session sources. Empty means all sources.
    pub allowed_sources: Vec<SessionSource>,
    /// Optional model provider filter. `None` means implementation default, while an empty vector
    /// means all providers.
    pub model_providers: Option<Vec<String>>,
    /// Whether archived threads should be listed instead of active threads.
    pub archived: bool,
    /// Optional exact working-directory filter.
    pub cwd: Option<PathBuf>,
    /// Optional substring/full-text search term for thread title/preview.
    pub search_term: Option<String>,
}

/// A page of stored thread records.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ThreadPage {
    /// Threads returned for this page.
    pub items: Vec<StoredThread>,
    /// Opaque cursor to continue listing.
    pub next_cursor: Option<String>,
    /// Number of backing rows/files/items scanned, when available.
    pub scanned: Option<usize>,
}

/// Store-owned thread metadata used by list/read/resume responses.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StoredThread {
    /// Thread id.
    pub thread_id: ThreadId,
    /// Source thread id when this thread was forked from another thread.
    pub forked_from_id: Option<ThreadId>,
    /// Legacy local rollout path, when the backing store has one.
    pub legacy_path: Option<PathBuf>,
    /// Tenant/owner metadata for multi-tenant stores.
    pub owner: ThreadOwner,
    /// Best available user-facing preview, usually the first user message.
    pub preview: String,
    /// Optional user-facing thread name/title.
    pub name: Option<String>,
    /// Model provider id associated with the thread.
    pub model_provider: String,
    /// Latest observed model, if known.
    pub model: Option<String>,
    /// Latest observed service tier, if known.
    pub service_tier: Option<ServiceTier>,
    /// Latest observed reasoning effort, if known.
    pub reasoning_effort: Option<ReasoningEffort>,
    /// Thread creation timestamp.
    pub created_at: DateTime<Utc>,
    /// Thread last-update timestamp.
    pub updated_at: DateTime<Utc>,
    /// Thread archive timestamp, if archived.
    pub archived_at: Option<DateTime<Utc>>,
    /// Working directory captured for the thread.
    pub cwd: PathBuf,
    /// Version of the CLI/app that created the thread.
    pub cli_version: String,
    /// Runtime source for the thread.
    pub source: SessionSource,
    /// Optional random nickname for thread-spawn sub-agents.
    pub agent_nickname: Option<String>,
    /// Optional role for thread-spawn sub-agents.
    pub agent_role: Option<String>,
    /// Optional canonical path for thread-spawn sub-agents.
    pub agent_path: Option<String>,
    /// Optional Git metadata captured for the thread.
    pub git_info: Option<GitInfo>,
    /// Approval mode captured for the thread.
    pub approval_mode: AskForApproval,
    /// Sandbox policy captured for the thread.
    pub sandbox_policy: SandboxPolicy,
    /// Last observed token usage.
    pub token_usage: Option<TokenUsage>,
    /// First user message observed for this thread, if any.
    pub first_user_message: Option<String>,
    /// Optional explicit memory mode, for example `disabled`.
    pub memory_mode: Option<String>,
    /// Persisted history, populated only when requested.
    pub history: Option<StoredThreadHistory>,
}

/// Parameters for setting a user-facing thread name.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SetThreadNameParams {
    /// Thread id to update.
    pub thread_id: ThreadId,
    /// Tenant/owner metadata for multi-tenant stores.
    pub owner: ThreadOwner,
    /// Normalized thread name.
    pub name: String,
}

/// Optional field patch where omission leaves a value unchanged and `Some(None)` clears it.
pub type OptionalStringPatch = Option<Option<String>>;

/// Patch for thread Git metadata.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct GitInfoPatch {
    /// Replacement commit SHA, clear request, or no-op.
    pub sha: OptionalStringPatch,
    /// Replacement branch name, clear request, or no-op.
    pub branch: OptionalStringPatch,
    /// Replacement origin URL, clear request, or no-op.
    pub origin_url: OptionalStringPatch,
}

/// Patch for mutable thread metadata.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct ThreadMetadataPatch {
    /// Optional user-facing thread title.
    pub name: OptionalStringPatch,
    /// Optional Git metadata patch.
    pub git_info: Option<GitInfoPatch>,
}

/// Parameters for patching mutable thread metadata.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct UpdateThreadMetadataParams {
    /// Thread id to update.
    pub thread_id: ThreadId,
    /// Tenant/owner metadata for multi-tenant stores.
    pub owner: ThreadOwner,
    /// Patch to apply.
    pub patch: ThreadMetadataPatch,
}

/// Parameters for archiving or unarchiving a thread.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ArchiveThreadParams {
    /// Thread id to archive or unarchive.
    pub thread_id: ThreadId,
    /// Tenant/owner metadata for multi-tenant stores.
    pub owner: ThreadOwner,
}

/// Parameters for finding a thread by its exact user-facing name.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct FindThreadByNameParams {
    /// Tenant/owner metadata for multi-tenant stores.
    pub owner: ThreadOwner,
    /// Exact normalized thread name to find.
    pub name: String,
    /// Whether archived threads are eligible.
    pub include_archived: bool,
    /// Optional exact working-directory filter.
    pub cwd: Option<PathBuf>,
    /// Allowed session sources. Empty means all sources.
    pub allowed_sources: Vec<SessionSource>,
    /// Optional model provider filter. `None` means implementation default, while an empty vector
    /// means all providers.
    pub model_providers: Option<Vec<String>>,
}

/// Parameters for resolving an old filesystem rollout path to a thread id.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ResolveLegacyPathParams {
    /// Filesystem rollout path supplied by legacy callers.
    pub path: PathBuf,
    /// Tenant/owner metadata for multi-tenant stores.
    pub owner: ThreadOwner,
    /// Whether archived threads are eligible.
    pub include_archived: bool,
}

/// Parameters for reading dynamic tool specs persisted for a thread.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DynamicToolsParams {
    /// Thread id to read.
    pub thread_id: ThreadId,
    /// Tenant/owner metadata for multi-tenant stores.
    pub owner: ThreadOwner,
}

/// Parameters for memory-mode lookups and pollution markers.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ThreadMemoryModeParams {
    /// Thread id to read or update.
    pub thread_id: ThreadId,
    /// Tenant/owner metadata for multi-tenant stores.
    pub owner: ThreadOwner,
}

/// Parameters for setting an explicit memory mode.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SetThreadMemoryModeParams {
    /// Thread id to update.
    pub thread_id: ThreadId,
    /// Tenant/owner metadata for multi-tenant stores.
    pub owner: ThreadOwner,
    /// Memory mode value to store, for example `disabled`.
    pub memory_mode: String,
}

/// Status of a parent-child thread-spawn edge.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ThreadSpawnEdgeStatus {
    /// Child thread is still active from the parent thread's perspective.
    Open,
    /// Child thread has been closed from the parent thread's perspective.
    Closed,
}

/// Parent-child relationship created by thread-spawn tools.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ThreadSpawnEdge {
    /// Parent thread id.
    pub parent_thread_id: ThreadId,
    /// Child thread id.
    pub child_thread_id: ThreadId,
    /// Current edge status.
    pub status: ThreadSpawnEdgeStatus,
}

/// Parameters for listing thread-spawn children or descendants.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ListThreadSpawnEdgesParams {
    /// Parent thread id to list from.
    pub thread_id: ThreadId,
    /// Tenant/owner metadata for multi-tenant stores.
    pub owner: ThreadOwner,
    /// Whether descendants should be traversed recursively.
    pub recursive: bool,
    /// Optional status filter.
    pub status: Option<ThreadSpawnEdgeStatus>,
}

/// Parameters for finding a thread-spawn child or descendant by canonical agent path.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct FindThreadSpawnByPathParams {
    /// Parent thread id to search from.
    pub thread_id: ThreadId,
    /// Tenant/owner metadata for multi-tenant stores.
    pub owner: ThreadOwner,
    /// Whether descendants should be searched recursively.
    pub recursive: bool,
    /// Canonical agent path to find.
    pub agent_path: String,
}
