packages:
  - codex-cli
  - codex-rs/responses-api-proxy/npm
  - sdk/typescript
  - shell-tool-mcp
  - google-workspace-mcp
  - google-drive-mcp

ignoredBuiltDependencies:
  - esbuild

minimumReleaseAge: 10080

blockExoticSubdeps: true
