packages:
  - codex-cli
  - codex-rs/responses-api-proxy/npm
  - sdk/typescript
  - shell-tool-mcp
  - vscode-extension
  - web

ignoredBuiltDependencies:
  - esbuild

minimumReleaseAge: 10080

blockExoticSubdeps: true
