// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for listing available reset credits.
 *
 * The upstream API counts every available credit but returns details for at most the first 10 and
 * does not expose a pagination cursor, so this method cannot truthfully expose `cursor` or `limit`.
 */
export type AccountRateLimitResetCreditListParams = Record<string, never>;
