// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountKind } from "./AccountKind";

/**
 * CODEZ - A short account summary for account switching UIs.
 */
export type AccountSummary = { name: string, kind?: AccountKind, email?: string, };
