// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RateLimitResetCredit } from "./RateLimitResetCredit";

/**
 * Available reset credits returned by the backend.
 *
 * This is a non-pageable snapshot because the upstream API does not expose a cursor. `data`
 * contains details for at most 10 credits, so it can contain fewer rows than `availableCount`.
 */
export type AccountRateLimitResetCreditListResponse = { availableCount: number, data: Array<RateLimitResetCredit>, };
