// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CODEZ - A short summary of a configured account.
 */
export type AccountKind = "chatgpt" | "apiKey";
