// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentCommunicationKind } from "./AgentCommunicationKind";
import type { AgentCommunicationState } from "./AgentCommunicationState";

export type AgentCommunication = { id: string, kind: AgentCommunicationKind, state: AgentCommunicationState, senderThreadId: string, receiverThreadId: string, content: string, sourceCallId: string | null, occurredAtMs: bigint, };
