// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selects who adjudicates approval requests once an action has already been
 * escalated for review. This does not disable separate safety checks such as
 * ARC.
 */
export type ApprovalsReviewer = "user" | "guardian_subagent";
