// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GranularApprovalConstraint } from "./GranularApprovalConstraint";

export type ApprovalPolicyConstraint = "untrusted" | "on-failure" | "on-request" | { "granular": GranularApprovalConstraint } | "never";
