// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppDisabledReason } from "./AppDisabledReason";

export type AppsDefaultConfig = { enabled: boolean, disabled_reason: AppDisabledReason | null, disable_destructive: boolean, disable_open_world: boolean, };
