// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

/**
 * EXPERIMENTAL - app tool metadata returned by app-list APIs.
 *
 * `input_schema` is the effective JSON Schema Codex will use for this
 * tool's parameters, including any connector link parameter constraints.
 */
export type AppToolInfo = { name: string, description: string | null, inputSchema: JsonValue, };
