// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AskUserQuestionRequest } from "../AskUserQuestionRequest";

export type AskUserQuestionParams = { threadId: string, turnId: string, callId: string, request: AskUserQuestionRequest, };
