// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AttestationGenerateResponse = {
/**
 * Opaque client attestation payload to embed in the upstream header envelope.
 */
headerValue: string, };
