// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodexAvatarBoxRules } from "./CodexAvatarBoxRules";
import type { CodexAvatarDefinition } from "./CodexAvatarDefinition";
import type { CodexAvatarOwnership } from "./CodexAvatarOwnership";
import type { CodexAvatarPityState } from "./CodexAvatarPityState";
import type { CodexAvatarRevealAward } from "./CodexAvatarRevealAward";

export type CodexAvatarInventoryReadResponse = { accountUserId: string, avatarDefinitions: Array<CodexAvatarDefinition>, ownedAvatars: Array<CodexAvatarOwnership>, equippedAvatarId: string, boxRules: CodexAvatarBoxRules, pityState: CodexAvatarPityState, pendingRevealAwards: Array<CodexAvatarRevealAward>, updatedAt: bigint, };
