// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CodexAvatarOwnership = { accountUserId: string, avatarId: string, firstUnlockedAt: bigint, lastAwardedAt: bigint, sourceSummary: string | null, };
