// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodexAvatarRarity } from "./CodexAvatarRarity";
import type { CodexAvatarStatus } from "./CodexAvatarStatus";

export type CodexAvatarDefinition = { avatarId: string, slug: string, displayName: string, description: string, rarity: CodexAvatarRarity, assetRef: string, status: CodexAvatarStatus, sortOrder: bigint, createdAt: bigint, updatedAt: bigint, };
