// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandAction } from "./CommandAction";
import type { ExecPolicyAmendment } from "./ExecPolicyAmendment";

export type CommandExecutionRequestApprovalParams = { threadId: string, turnId: string, itemId: string, 
/**
 * Unique identifier for this specific approval callback.
 *
 * For regular shell/unified_exec approvals, this is the same as
 * `itemId` (one approval callback per command item).
 *
 * For zsh-sidecar subcommand approvals, multiple callbacks can belong to
 * one parent `itemId`, so `approvalId` is a distinct opaque callback id
 * (a UUID) used to disambiguate routing.
 */
approvalId: string, 
/**
 * Optional explanatory reason (e.g. request for network access).
 */
reason?: string | null, 
/**
 * The command to be executed.
 */
command?: string | null, 
/**
 * The command's working directory.
 */
cwd?: string | null, 
/**
 * Best-effort parsed command actions for friendly display.
 */
commandActions?: Array<CommandAction> | null, 
/**
 * Optional proposed execpolicy amendment to allow similar commands without prompting.
 */
proposedExecpolicyAmendment?: ExecPolicyAmendment | null, };
