// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandExecTerminalSize } from "./CommandExecTerminalSize";
import type { SandboxPolicy } from "./SandboxPolicy";

export type CommandExecParams = { command: Array<string>, processId?: string | null, tty?: boolean, streamStdin?: boolean, streamStdoutStderr?: boolean, outputBytesCap?: number | null, disableOutputCap?: boolean, disableTimeout?: boolean, timeoutMs?: number | null, cwd?: string | null, env?: { [key in string]?: string | null } | null, size?: CommandExecTerminalSize | null, sandboxPolicy?: SandboxPolicy | null, };
