// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LegacyAppPathString } from "../LegacyAppPathString";
import type { CommandAction } from "./CommandAction";
import type { CommandExecutionApprovalPurpose } from "./CommandExecutionApprovalPurpose";
import type { ExecPolicyAmendment } from "./ExecPolicyAmendment";
import type { NetworkApprovalContext } from "./NetworkApprovalContext";
import type { NetworkPolicyAmendment } from "./NetworkPolicyAmendment";

export type CommandExecutionRequestApprovalParams = {threadId: string, turnId: string, itemId: string, /**
 * Unix timestamp (in milliseconds) when this approval request started.
 */
startedAtMs: number, /**
 * Opaque identifier for this specific approval callback, when present.
 *
 * Use the JSON-RPC request ID for the response. When tracking callback UI
 * or state outside that envelope, use this instead of `itemId` when it is
 * present. Absence is a legacy/cacheable compatibility path.
 */
approvalId?: string | null, /**
 * Semantic purpose of this approval request. Compatibility events may omit it.
 */
approvalPurpose?: CommandExecutionApprovalPurpose | null, /**
 * Environment in which the command will run.
 */
environmentId: string | null, /**
 * Optional explanatory reason (e.g. request for network access).
 */
reason?: string | null, /**
 * Optional context for a managed-network approval prompt.
 */
networkApprovalContext?: NetworkApprovalContext | null, /**
 * The command to be executed.
 */
command?: string | null, /**
 * The command's working directory.
 */
cwd?: LegacyAppPathString | null, /**
 * Best-effort parsed command actions for friendly display.
 */
commandActions?: Array<CommandAction> | null, /**
 * Optional proposed execpolicy amendment to allow similar commands without prompting.
 */
proposedExecpolicyAmendment?: ExecPolicyAmendment | null, /**
 * Optional proposed network policy amendments (allow/deny host) for future requests.
 */
proposedNetworkPolicyAmendments?: Array<NetworkPolicyAmendment> | null};
