// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommandExecutionOutputDeltaNotification = { threadId: string, turnId: string, itemId: string, 
/**
 * Best-effort UTF-8 view of the output chunk for backwards compatibility.
 */
delta: string, 
/**
 * Exact raw bytes for the chunk, base64-encoded.
 */
deltaBase64: string | null, };
