// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type ConfigHostSetParams = {
/**
 * Full replacement app-server host config layer, shaped like config.toml.
 * An empty object clears the host config layer.
 */
config: { [key in string]?: JsonValue }, };
