// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigRequirementsPatternToken } from "./ConfigRequirementsPatternToken";
import type { ConfigRequirementsRuleDecision } from "./ConfigRequirementsRuleDecision";

export type ConfigRequirementsPrefixRule = { pattern: Array<ConfigRequirementsPatternToken>, decision: ConfigRequirementsRuleDecision | null, justification: string | null, };
