// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextCompactionKind } from "./ContextCompactionKind";

/**
 * Deprecated: Use `ContextCompaction` item type instead.
 */
export type ContextCompactedNotification = { threadId: string, turnId: string, kind?: ContextCompactionKind, };
