// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Register or replace a named execution environment.
 */
export type EnvironmentRegisterParams = {
/**
 * Logical environment identifier used by thread and fs APIs.
 */
environmentId: string,
/**
 * Optional exec-server websocket URL; omit for local execution.
 */
execServerUrl?: string | null, };
