// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * List named execution environments registered with the app-server.
 */
export type EnvironmentListParams = { cursor?: string | null, limit?: number | null, };
