// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExperimentalFeatureOverridesSetResponse = { 
/**
 * The active process-wide feature flag overrides after the update.
 */
overrides: { [key in string]?: boolean }, };
