// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExperimentalFeatureListParams = {
/**
 * Opaque pagination cursor returned by a previous call.
 */
cursor?: string | null,
/**
 * Optional page size; defaults to a reasonable server-side value.
 */
limit?: number | null,
/**
 * Working directory used to resolve project-local config when computing
 * feature enablement. Pass `cwd` when available so `enabled` is computed
 * with the same project-local config layers that apply to that workspace or
 * thread; if omitted, the server uses its default config resolution
 * context.
 */
cwd?: string | null, };
