// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExperimentalFeatureOverridesSetParams = { 
/**
 * Process-wide feature flag overrides keyed by canonical feature name.
 *
 * This replaces the current in-memory override set. Send an empty map to
 * clear all overrides.
 */
overrides: { [key in string]?: boolean }, };
