// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalMigrationScope } from "./ExternalMigrationScope";
import type { ExternalMigrationSource } from "./ExternalMigrationSource";
import type { ExternalMigrationState } from "./ExternalMigrationState";

export type ExternalMigrationApplyResponse = { source: ExternalMigrationSource, scope: ExternalMigrationScope, state: ExternalMigrationState, repoRoot: string | null, importedConfigKeys: Array<string>, copiedSkills: Array<string>, copiedAgentsMd: boolean, importedMcpServers: Array<string>, };
