// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalMigrationDetected = { claudeHomeExists: boolean | null, settingsJson: boolean | null, claudeMd: boolean, skillsCount: number | null, agentsMdExists: boolean | null, mcpJson: boolean | null, priorCodexThreadCount: number | null, };
