// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalAgentConfigImportRawError } from "./ExternalAgentConfigImportRawError";
import type { ExternalAgentConfigImportSuccess } from "./ExternalAgentConfigImportSuccess";
import type { ExternalAgentConfigMigrationItemType } from "./ExternalAgentConfigMigrationItemType";

export type ExternalAgentConfigImportItemResult = { itemType: ExternalAgentConfigMigrationItemType, description: string, cwd: string | null, successCount: number, errorCount: number, successes: Array<ExternalAgentConfigImportSuccess>, rawErrors: Array<ExternalAgentConfigImportRawError>, };
