// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalMigrationAction } from "./ExternalMigrationAction";
import type { ExternalMigrationScope } from "./ExternalMigrationScope";
import type { ExternalMigrationSource } from "./ExternalMigrationSource";

export type ExternalMigrationApplyParams = { source: ExternalMigrationSource, scope: ExternalMigrationScope, action: ExternalMigrationAction, cwd?: string | null, };
