// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalAgentConfigImportMigrationDetailsParams } from "./ExternalAgentConfigImportMigrationDetailsParams";
import type { ExternalAgentConfigMigrationItemType } from "./ExternalAgentConfigMigrationItemType";

export type ExternalAgentConfigImportMigrationItem = { itemType: ExternalAgentConfigMigrationItemType, description: string,
/**
 * Null or empty means home-scoped migration; non-empty means repo-scoped migration.
 */
cwd: string | null, details: ExternalAgentConfigImportMigrationDetailsParams | null, };
