// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalAgentConfigImportSource } from "./ExternalAgentConfigImportSource";
import type { ExternalAgentConfigMigrationItem } from "./ExternalAgentConfigMigrationItem";

export type ExternalAgentConfigImportParams = { migrationItems: Array<ExternalAgentConfigMigrationItem>,
/**
 * Source product that produced the migration items. Missing means Claude Code for
 * compatibility with older clients.
 */
source?: ExternalAgentConfigImportSource | null, };
