// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalAgentConfigImportMigrationItem } from "./ExternalAgentConfigImportMigrationItem";

export type ExternalAgentConfigImportParams = { migrationItems: Array<ExternalAgentConfigImportMigrationItem>, };
