// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalMigrationProposed = { configKeys: Array<string>, copyAgentsMd: boolean, skillsToCopy: Array<string>, mcpServersToAdd: Array<string>, };
