// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

/**
 * Resolve an absolute path to its canonical filesystem path.
 */
export type FsCanonicalizeParams = {
/**
 * Absolute path to canonicalize. The path must exist.
 */
path: AbsolutePathBuf, };
