// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

/**
 * Canonical path returned by `fs/canonicalize`.
 */
export type FsCanonicalizeResponse = {
/**
 * Canonical absolute path with symbolic links resolved.
 */
path: AbsolutePathBuf, };
