// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Successful response for `fs/readFile/open`.
 */
export type FsReadFileOpenResponse = {
/**
 * Maximum decoded bytes returned by one read.
 */
maxChunkBytes: number, };
