// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

/**
 * List direct child names for a directory.
 */
export type FsReadDirectoryParams = {
/**
 * Absolute directory path to read.
 */
path: AbsolutePathBuf,
/**
 * Optional environment selection. Use `"local"` or `"remote"`, or omit
 * the field to use the default environment.
 */
environmentId?: string | null, };
