// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

/**
 * Open a destination-local temporary file for streamed writes.
 */
export type FsWriteFileOpenParams = {
/**
 * Client-supplied handle identifier scoped to this connection.
 */
handleId: string,
/**
 * Absolute destination path.
 */
path: AbsolutePathBuf, };
