// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata returned after a successful write commit.
 */
export type FsWriteFileCommitResponse = { sizeBytes: number, modifiedAtMs: number, };
