// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GranularApprovalConfig } from "./GranularApprovalConfig";
import type { GranularApprovalWildcard } from "./GranularApprovalWildcard";

export type GranularApprovalConstraint = GranularApprovalWildcard | GranularApprovalConfig;
