// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [UNSTABLE] Whether a denied action can be explicitly approved for one retry.
 */
export type GuardianDenialKind = "soft" | "denial";
