// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoReviewDecisionSource } from "./AutoReviewDecisionSource";
import type { GuardianApprovalReviewAction } from "./GuardianApprovalReviewAction";
import type { GuardianApprovalReviewStatus } from "./GuardianApprovalReviewStatus";
import type { GuardianRiskLevel } from "./GuardianRiskLevel";
import type { GuardianUserAuthorization } from "./GuardianUserAuthorization";

export type GuardianAssessmentEvent = { id: string, targetItemId: string | null, turnId: string, startedAtMs: number, completedAtMs: number, status: GuardianApprovalReviewStatus, riskLevel: GuardianRiskLevel | null, userAuthorization: GuardianUserAuthorization | null, rationale: string | null, decisionSource: AutoReviewDecisionSource | null, action: GuardianApprovalReviewAction, };
