// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HttpStateSetParams = { state: string,
/**
 * Write only if the calling surface still stores this state. Omit or set
 * to null for an unconditional replacement.
 */
expectedState?: string | null, };
