// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GuardianApprovalReview } from "./GuardianApprovalReview";

/**
 * [UNSTABLE] Temporary notification payload for guardian automatic approval
 * review. This shape is expected to change soon.
 */
export type ItemGuardianApprovalReviewCompletedNotification = { threadId: string, turnId: string, targetItemId: string, review: GuardianApprovalReview, };
