// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountSummary } from "./AccountSummary";

/**
 * CODEZ - List available accounts (multi-account support).
 */
export type ListAccountsResponse = { activeAccount?: string, accounts: Array<AccountSummary>, };
