// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadActiveFlag } from "./ThreadActiveFlag";
import type { ThreadTerminalOutcome } from "./ThreadTerminalOutcome";

export type LoadedThreadStatus = { "type": "idle" } | { "type": "active", activeFlags: Array<ThreadActiveFlag>, } | { "type": "terminal", outcome: ThreadTerminalOutcome, };
