// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { MarketplaceSourceType } from "./MarketplaceSourceType";

export type MarketplaceListEntry = { name: string, path: AbsolutePathBuf, lastUpdated: string | null, sourceType: MarketplaceSourceType | null, source: string | null, refName: string | null, sparsePaths: Array<string>, };
