// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpElicitationRequestParams = { threadId: string, serverName: string, requestId: string | number, message: string, };
