// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerStartupStatus } from "./McpServerStartupStatus";

export type McpServerStartupUpdatedNotification = { threadId: string, server: string, status: McpServerStartupStatus, };
