// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NativeIntegrityStateWriteParams = { state: string,
/**
 * When present, write only if the calling surface still stores this state.
 */
expectedState?: string | null, };
