// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionPromptType } from "./PermissionPromptType";

/**
 * Metadata for displaying a permission prompt when decision is AskUser.
 */
export type PermissionPromptMetadata = { 
/**
 * Type of permission being requested
 */
promptType: PermissionPromptType, 
/**
 * Human-readable description of the operation
 */
description: string, 
/**
 * For bash: the command being executed
 */
command?: string, 
/**
 * For file operations: the target file path
 */
filePath?: string, 
/**
 * For MCP/API: the tool or endpoint name
 */
toolName?: string, };
