// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalsReviewer } from "./ApprovalsReviewer";
import type { AskForApproval } from "./AskForApproval";
import type { PermissionPresetId } from "./PermissionPresetId";
import type { SandboxPolicy } from "./SandboxPolicy";

/**
 * Request sent to app clients when a model asks to switch permission modes.
 *
 * Core resolves the requested preset before emitting this payload, so clients
 * should render the provided settings and label rather than recomputing policy
 * choices from the preset id.
 */
export type PermissionPresetRequestApprovalParams = { threadId: string, turnId: string, itemId: string, preset: PermissionPresetId, label: string, description: string, approvalPolicy: AskForApproval, approvalsReviewer: ApprovalsReviewer, sandboxPolicy: SandboxPolicy, reason: string | null, };
