// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PermissionProfileSelectionParams = {
/**
 * Select a named built-in or user-defined profile. This updates profile
 * identity metadata only; it does not replace the thread's effective
 * permissions profile.
 */
id: string, };
