// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionPresetId } from "./PermissionPresetId";

/**
 * Request sent to app clients when a model asks to switch permission modes.
 *
 * Clients should open their local permission picker with the requested preset
 * preselected, allowing the user to accept it or choose a different preset.
 */
export type PermissionPresetRequestApprovalParams = { threadId: string, turnId: string, itemId: string, preset: PermissionPresetId, reason: string | null, };
