// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionPresetApprovalDecision } from "./PermissionPresetApprovalDecision";
import type { PermissionPresetId } from "./PermissionPresetId";

/**
 * Response from an app client after the permission preset picker resolves.
 */
export type PermissionPresetRequestApprovalResponse = { decision: PermissionPresetApprovalDecision, preset: PermissionPresetId, };
