// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Type of permission prompt to display when decision is AskUser.
 */
export type PermissionPromptType = "bash" | "file_write" | "mcp_mutation" | "api_mutation";
