// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalsReviewer } from "./ApprovalsReviewer";
import type { AskForApproval } from "./AskForApproval";

export type PermissionPreset = { id: string, permissionProfileId: string, description: string | null, approvalPolicy: AskForApproval, approvalsReviewer: ApprovalsReviewer, isDefault: boolean, };
