// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A built-in permission-mode preset that app clients can confirm.
 */
export type PermissionPresetId = "auto" | "full-access" | "read-only" | "guardian-approvals";
