// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GrantedPermissionProfile } from "./GrantedPermissionProfile";
import type { PermissionGrantScope } from "./PermissionGrantScope";

/**
 * Response from an app client after the narrow permission grant UI resolves.
 *
 * Returning an empty permission profile is a denial. Returning a non-empty
 * profile grants only those permissions, and core applies them for the
 * specified scope.
 */
export type PermissionsRequestApprovalResponse = { permissions: GrantedPermissionProfile, scope: PermissionGrantScope, };
