// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Final process exit notification for `process/spawn`.
 */
export type ProcessExitedNotification = {
/**
 * Client-supplied, connection-scoped `processHandle` from `process/spawn`.
 */
processHandle: string,
/**
 * Process exit code.
 */
exitCode: number,
/**
 * Buffered stdout capture.
 *
 * Empty when stdout was streamed via `process/outputDelta`.
 */
stdout: string,
/**
 * Buffered stderr capture.
 *
 * Empty when stderr was streamed via `process/outputDelta`.
 */
stderr: string, };
