// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteControlConnectionState } from "./RemoteControlConnectionState";

/**
 * Current remote-control connection state and environment id exposed to clients.
 */
export type RemoteControlStatusChangedNotification = { state: RemoteControlConnectionState, environmentId: string | null, };
