// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewStoryStepReadiness } from "./ReviewStoryStepReadiness";

export type ReviewStoryStep = { stepId: string, index: number, title: string, goal: string, summary: string, dependencyRationale: string, anchorIds: Array<string>, reviewFocus: Array<string>, readiness: ReviewStoryStepReadiness, error: string | null, };
