// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewStorySnapshotSummary } from "./ReviewStorySnapshotSummary";

export type ReviewStoryListResponse = { data: Array<ReviewStorySnapshotSummary>, nextCursor: string | null, };
