// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewStoryAnchor } from "./ReviewStoryAnchor";
import type { ReviewStorySnapshotStatus } from "./ReviewStorySnapshotStatus";
import type { ReviewStoryStep } from "./ReviewStoryStep";
import type { ReviewTarget } from "./ReviewTarget";

export type ReviewStorySnapshot = { storySnapshotId: string, threadId: string, title: string, overview: string, target: ReviewTarget, sourceFingerprint: string, status: ReviewStorySnapshotStatus, createdAt: bigint, updatedAt: bigint, previousStorySnapshotId: string | null, stale: boolean, steps: Array<ReviewStoryStep>, anchors: Array<ReviewStoryAnchor>, };
