// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShellEnvironmentPolicyInherit } from "./ShellEnvironmentPolicyInherit";

export type ShellEnvironmentPolicyRequirements = { inherit: ShellEnvironmentPolicyInherit | null, ignore_default_excludes: boolean | null, exclude: { [key in string]?: boolean } | null, set: { [key in string]?: string } | null, include_only: { [key in string]?: boolean } | null, experimental_use_profile: boolean | null, };
