// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Notification emitted when local skill files or skill configuration changes.
 */
export type SkillsUpdatedNotification = Record<string, never>;
