// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Notification emitted when the server's local skill view changes.
 *
 * The payload is intentionally empty because clients should treat this as a
 * refresh hint and call `skills/list` again, typically with `forceReload:
 * true`, instead of trying to apply an incremental update.
 */
export type SkillsUpdatedNotification = Record<string, never>;
