// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillRoot } from "./SkillRoot";

export type SkillsListParams = { 
/**
 * When empty, defaults to the current session working directory.
 */
cwds?: Array<string>, 
/**
 * Additional skill roots to scan alongside the defaults.
 */
additionalRoots?: Array<SkillRoot>, 
/**
 * When true, bypass the skills cache and re-scan skills from disk.
 */
forceReload?: boolean, };
