// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SkillsListParams = {
/**
 * Working directories used to list skills. Must be empty when `threadId` is provided. When
 * empty, defaults to the loaded thread's cwd or the app-server default cwd.
 */
cwds?: Array<string>,
/**
 * Optional loaded thread id used to evaluate skills from that thread's cwd and config. Cannot
 * be combined with `cwds`.
 */
threadId?: string | null,
/**
 * When true, bypass the skills cache and re-scan skills from disk.
 */
forceReload?: boolean, };
