// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SkillProvenance = "personal" | "project" | "system" | "admin" | "openai_marketplace" | "workspace_marketplace" | "custom_marketplace" | "local_plugin" | "debug_plugin" | "ad_hoc_plugin";
