// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CODEZ - Switch the active account (multi-account support).
 */
export type SwitchAccountParams = { name: string, createIfMissing: boolean, };
