// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Personality } from "../Personality";
import type { ReasoningEffort } from "../ReasoningEffort";
import type { ReasoningSummary } from "../ReasoningSummary";
import type { WindowsSandboxLevel } from "../WindowsSandboxLevel";
import type { AskForApproval } from "./AskForApproval";
import type { SandboxPolicy } from "./SandboxPolicy";

export type ThreadContextUpdateParams = {threadId: string, cwd?: string | null, approvalPolicy?: AskForApproval | null, sandboxPolicy?: SandboxPolicy | null, windowsSandboxLevel?: WindowsSandboxLevel | null, model?: string | null, effort?: ReasoningEffort | null | null, summary?: ReasoningSummary | null, personality?: Personality | null};
