// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadArchiveParams = { threadId: string,
/**
 * Whether to archive spawned subagent descendants. Defaults to true for
 * compatibility with the legacy `thread/archive` behavior.
 */
includeDescendants?: boolean | null, };
