// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadNetworkProxyRuntime } from "./ThreadNetworkProxyRuntime";
import type { ThreadSettings } from "./ThreadSettings";

export type ThreadSettingsUpdatedNotification = { threadId: string, threadSettings: ThreadSettings,
/**
 * Latest live managed-proxy runtime, or `null` when the proxy is inactive.
 */
networkProxy: ThreadNetworkProxyRuntime | null, };
