// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Live managed-proxy details for a thread running on the app-server host.
 */
export type ThreadNetworkProxyRuntime = { httpAddr: string, socksAddr: string,
/**
 * Whether the proxy intercepts TLS with a managed certificate authority.
 */
mitm: boolean, };
