// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * EXPERIMENTAL - realtime start response protocol payload.
 */
export type ThreadRealtimeStartResponseProtocol = { "type": "jsonRpcPcm" } | { "type": "rtc", answerSdp: string, };
