// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimerDelivery } from "./TimerDelivery";
import type { TimerTrigger } from "./TimerTrigger";

export type ThreadTimer = { id: string, trigger: TimerTrigger, prompt: string, delivery: TimerDelivery, createdAt: number, nextRunAt: number | null, lastRunAt: number | null, };
