// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RealtimeTranscriptUpdateKind } from "../RealtimeTranscriptUpdateKind";

/**
 * EXPERIMENTAL - flat transcript update emitted whenever realtime
 * transcript text changes or completes.
 */
export type ThreadRealtimeTranscriptUpdatedNotification = { threadId: string, role: string,
/**
 * Delta text for delta updates; final complete text for done updates.
 */
text: string, updateKind: RealtimeTranscriptUpdateKind, };
