// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * EXPERIMENTAL - realtime start protocol selected by the client.
 */
export type ThreadRealtimeStartProtocol = { "type": "jsonRpcPcm" } | { "type": "rtc", offerSdp: string, };
