// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadRealtimeTranscriptEntry } from "./ThreadRealtimeTranscriptEntry";

/**
 * EXPERIMENTAL - flat transcript snapshot emitted when realtime hands off to
 * the main agent.
 */
export type ThreadRealtimeTranscriptAddedNotification = { threadId: string, handoffId: string, itemId: string, transcript: Array<ThreadRealtimeTranscriptEntry>, };
