// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Optional caller-supplied classification of who or what owns a thread's execution.
 */
export type ThreadSource = "user" | "subagent" | "system" | "automation" | "memory_consolidation";
