// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadMetadataGitInfoUpdateParams } from "./ThreadMetadataGitInfoUpdateParams";

export type ThreadMetadataUpdateParams = { threadId: string, 
/**
 * Patch the stored Git metadata for this thread. Only non-null fields are updated.
 */
gitInfo?: ThreadMetadataGitInfoUpdateParams | null, };
