// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadShellCommandParams = { threadId: string, 
/**
 * Shell command string evaluated by the thread's configured shell.
 * Unlike `command/exec`, this intentionally preserves shell syntax
 * such as pipes, redirects, and quoting for legacy `!` parity.
 */
command: string, };
