// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { ThreadBackgroundTerminalStatus } from "./ThreadBackgroundTerminalStatus";

export type ThreadBackgroundTerminal = { itemId: string, processId: string, command: string, cwd: AbsolutePathBuf, startedAt: bigint, status: ThreadBackgroundTerminalStatus, osPid: number | null, cpuPercent: number | null, rssKb: bigint | null, };
