// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadRealtimeTranscriptEntry } from "./ThreadRealtimeTranscriptEntry";

/**
 * EXPERIMENTAL - flat transcript snapshot emitted whenever realtime
 * transcript text changes.
 */
export type ThreadRealtimeTranscriptUpdatedNotification = { threadId: string, transcript: Array<ThreadRealtimeTranscriptEntry>, };
