// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadedThreadEntry } from "./LoadedThreadEntry";

export type ThreadWatchUpdate = { "type": "upsert", entry: LoadedThreadEntry, } | { "type": "remove", threadId: string, } | { "type": "resyncRequired" };
