// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalsReviewer } from "./ApprovalsReviewer";
import type { AskForApproval } from "./AskForApproval";
import type { SandboxPolicy } from "./SandboxPolicy";
import type { ThreadGoalStatus } from "./ThreadGoalStatus";

export type ThreadGoalSetParams = {threadId: string, objective?: string | null, status?: ThreadGoalStatus | null, /**
 * Override the approval policy before a goal continuation can start.
 */
approvalPolicy?: AskForApproval | null, /**
 * Override where approval requests are routed before a goal continuation can start.
 */
approvalsReviewer?: ApprovalsReviewer | null, /**
 * Override the sandbox policy before a goal continuation can start.
 */
sandboxPolicy?: SandboxPolicy | null, tokenBudget?: number | null};
