// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResponseItem } from "../ResponseItem";

export type ThreadInjectItemsParams = { threadId: string,
/**
 * Responses API items to append to the thread's model-visible history.
 */
items: Array<ResponseItem>, };
