// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadNetworkProxyRuntime } from "./ThreadNetworkProxyRuntime";

/**
 * Extra app-server data for a thread.
 */
export type ThreadExtra = {
/**
 * Runtime endpoints for the managed network proxy owned by this live thread.
 */
networkProxy: ThreadNetworkProxyRuntime | null, };
