// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { AskForApproval } from "./AskForApproval";
import type { SandboxMode } from "./SandboxMode";

/**
 * There are two ways to fork a thread:
 * 1. By thread_id: load the thread from disk by thread_id and fork it into a new thread.
 * 2. By path: load the thread from disk by path and fork it into a new thread.
 *
 * If using path, the thread_id param will be ignored.
 *
 * Prefer using thread_id whenever possible.
 */
export type ThreadForkParams = {threadId: string, /**
 * [UNSTABLE] Specify the rollout path to fork from.
 * If specified, the thread_id param will be ignored.
 */
path?: string | null, /**
 * [UNSTABLE] Fork after the specified historical turn (inclusive).
 * When omitted, the full thread history is copied.
 *
 * The value should come from `thread/read(includeTurns=true)` for the same source thread.
 * Requests are rejected for legacy histories whose replayed turn ids are not stable, for
 * in-progress turns, and for turns that do not yet contain both a user message and an agent
 * response.
 */
forkAfterTurnId?: string | null, /**
 * Configuration overrides for the forked thread, if any.
 */
model?: string | null, modelProvider?: string | null, cwd?: string | null, approvalPolicy?: AskForApproval | null, sandbox?: SandboxMode | null, config?: { [key in string]?: JsonValue } | null, baseInstructions?: string | null, developerInstructions?: string | null, /**
 * If true, persist additional rollout EventMsg variants required to
 * reconstruct a richer thread history on subsequent resume/fork/read.
 */
persistExtendedHistory: boolean};
