// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Turn } from "./Turn";

export type ThreadTurnsListResponse = { data: Array<Turn>, 
/**
 * Opaque cursor to pass to the next call to continue after the last turn.
 * if None, there are no more turns to return.
 */
nextCursor: string | null, 
/**
 * Opaque cursor to pass as `cursor` when reversing `sortDirection`.
 * if None, the page contained no turns.
 */
backwardsCursor: string | null, };
