// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadSearchTextRange } from "./ThreadSearchTextRange";

export type ThreadSearchOccurrence = { threadId: string, turnId: string, itemId: string,
/**
 * Stable identity for this occurrence within the persisted query snapshot.
 */
occurrenceId: string,
/**
 * Zero-based occurrence index within the user or assistant message item.
 */
occurrenceIndex: number, snippet: string,
/**
 * Match range within the complete item text, in UTF-16 code units.
 */
matchRange: ThreadSearchTextRange,
/**
 * Match range within `snippet`, in UTF-16 code units.
 */
snippetMatchRange: ThreadSearchTextRange,
/**
 * Unix timestamp in seconds used to place the matching turn chronologically.
 */
turnStartedAt: number,
/**
 * Opaque inclusive cursor accepted by `thread/turns/list` for this turn.
 */
turnCursor: string, };
