// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * EXPERIMENTAL. Defines a single selectable option for request_option_picker.
 */
export type ToolOptionPickerOption = { label: string, description: string | null, };
