// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { ToolCallType } from "./ToolCallType";

/**
 * Request parameters for PreToolUse hook.
 * Sent to client BEFORE any tool execution to allow interception.
 */
export type ToolCallPreExecuteParams = { threadId: string, turnId: string, itemId: string, 
/**
 * The type of tool being executed.
 */
toolType: ToolCallType, 
/**
 * The name of the tool (e.g., "bash", "mcp__github__create_issue").
 */
toolName: string, 
/**
 * The tool input as JSON. Structure depends on tool_type.
 */
input: JsonValue, 
/**
 * For MCP tools: the server name.
 */
mcpServer?: string, 
/**
 * For MCP tools: the actual tool name within the server.
 */
mcpTool?: string, };
