// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolSetupCodexContextPickerAction } from "./ToolSetupCodexContextPickerAction";

/**
 * EXPERIMENTAL. Captures a user's response to setup_codex_context_picker.
 */
export type ToolSetupCodexContextPickerResponse = { action: ToolSetupCodexContextPickerAction, selectedSources: Array<string>, };
