// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { PermissionPromptMetadata } from "./PermissionPromptMetadata";
import type { UserPermissionDecision } from "./UserPermissionDecision";

/**
 * Decision for PreToolUse hook response.
 */
export type ToolCallPreExecuteDecision = "allow" | { "block": { 
/**
 * Error message to return to the model (guides retry behavior).
 */
reason: string, } } | { "modify": { 
/**
 * Modified input to use instead of the original.
 */
input: JsonValue, } } | { "askUser": { 
/**
 * Metadata for displaying the permission prompt
 */
prompt: PermissionPromptMetadata, } } | { "userResponse": { 
/**
 * The user's decision
 */
decision: UserPermissionDecision, 
/**
 * If true, auto-approve similar operations for the rest of the session
 */
accept_for_session: boolean, } };
