// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * EXPERIMENTAL. Params sent with a setup_codex_context_picker event.
 */
export type ToolSetupCodexContextPickerParams = { threadId: string, turnId: string, itemId: string, };
