// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * EXPERIMENTAL. Action selected for request_option_picker.
 */
export type ToolOptionPickerAction = "submit" | "skip" | "dismiss";
