// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * EXPERIMENTAL. Action selected for setup_codex_context_picker.
 */
export type ToolSetupCodexContextPickerAction = "continue" | "skip" | "dismiss";
