// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddCreditsNudgeCreditType } from "./AddCreditsNudgeCreditType";
import type { TrackUsageLimitBannerAction } from "./TrackUsageLimitBannerAction";

export type TrackUsageLimitBannerParams = { action: TrackUsageLimitBannerAction, creditType: AddCreditsNudgeCreditType, };
