// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WindowsSandboxLevel } from "../WindowsSandboxLevel";
import type { ActivePermissionProfile } from "./ActivePermissionProfile";
import type { TurnEnvironmentPermissionProfileParams } from "./TurnEnvironmentPermissionProfileParams";

export type TurnEnvironmentSandboxParams = { permissionProfile: TurnEnvironmentPermissionProfileParams, activePermissionProfile?: ActivePermissionProfile | null, windowsSandboxLevel: WindowsSandboxLevel, windowsSandboxPrivateDesktop: boolean, useLegacyLandlock: boolean, };
