// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkAccess } from "./NetworkAccess";
import type { TurnEnvironmentManagedFileSystemPermissionsParams } from "./TurnEnvironmentManagedFileSystemPermissionsParams";

export type TurnEnvironmentPermissionProfileParams = { "type": "managed", file_system: TurnEnvironmentManagedFileSystemPermissionsParams, network: NetworkAccess, } | { "type": "disabled" } | { "type": "external", network: NetworkAccess, };
