// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TurnToolAttribution = { id: string, kind: string, name: string | null, server: string | null, pluginId: string | null, };
