// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalsReviewer } from "./ApprovalsReviewer";
import type { AskForApproval } from "./AskForApproval";

export type TurnOverrideActiveContextParams = { threadId: string,
/**
 * Required active turn id precondition. The request fails when it does not
 * match the currently active turn.
 */
expectedTurnId: string,
/**
 * Override the active turn approval policy and the default for subsequent
 * turns.
 */
approvalPolicy?: AskForApproval | null,
/**
 * Override where approval requests are routed for review on the active
 * turn and subsequent turns.
 */
approvalsReviewer?: ApprovalsReviewer | null, };
