// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileSystemSandboxEntry } from "./FileSystemSandboxEntry";

export type TurnEnvironmentManagedFileSystemPermissionsParams = { "type": "restricted", entries: Array<FileSystemSandboxEntry>, glob_scan_max_depth?: number, } | { "type": "unrestricted" };
