// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserInput } from "./UserInput";

export type TurnSteerParams = { threadId: string, input: Array<UserInput>, 
/**
 * Optional active turn id precondition. If specified and the current active
 * turn does not match, the request fails.
 */
expectedTurnId?: string | null, };
