// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnAppAttribution } from "./TurnAppAttribution";
import type { TurnPluginAttribution } from "./TurnPluginAttribution";
import type { TurnSkillAttribution } from "./TurnSkillAttribution";
import type { TurnToolAttribution } from "./TurnToolAttribution";

export type TurnAttribution = { skills: Array<TurnSkillAttribution>, plugins: Array<TurnPluginAttribution>, apps: Array<TurnAppAttribution>, tools: Array<TurnToolAttribution>, };
