// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiPathString } from "../ApiPathString";

export type TurnEnvironmentParams = { environmentId: string,
/**
 * Absolute cwd rendered using the selected environment's path convention.
 */
cwd: ApiPathString, };
