// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LegacyAppPathString } from "../LegacyAppPathString";
import type { SandboxPolicy } from "./SandboxPolicy";

export type TurnEnvironmentParams = { environmentId: string, cwd: LegacyAppPathString,
/**
 * Environment-native runtime workspace roots. Omitted defaults to `cwd`.
 */
runtimeWorkspaceRoots?: Array<LegacyAppPathString> | null,
/**
 * Sandbox permissions for this environment. Omitted inherits the thread sandbox.
 */
sandbox?: SandboxPolicy | null, };
