// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WellbeingProtectionResult } from "./WellbeingProtectionResult";

export type TurnProtectionResultNotification = { threadId: string, turnId: string, wellbeing: WellbeingProtectionResult, };
