// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicToolSchemaErrorTool } from "./DynamicToolSchemaErrorTool";

export type TurnErrorData = { "reason": "dynamicToolInputSchema", backend: string, tool: DynamicToolSchemaErrorTool | null, toolCandidates: Array<DynamicToolSchemaErrorTool>, schemaPath: string | null, underlyingError: string, remediation: string, };
