// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallationMethod } from "./InstallationMethod";

export type UpdateCheckResponse = { currentVersion: string, latestVersion: string, installationMethod: InstallationMethod, canAutoUpdate: boolean, };
