// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageDetail } from "../ImageDetail";
import type { TextElement } from "./TextElement";

export type UserInput = { "type": "text", clientId?: string, text: string,
/**
 * UI-defined spans within `text` used to render or persist special elements.
 */
text_elements: Array<TextElement>, } | { "type": "image", clientId?: string, detail?: ImageDetail, url: string, } | { "type": "localImage", clientId?: string, detail?: ImageDetail, path: string, } | { "type": "skill", clientId?: string, name: string, path: string, } | { "type": "mention", clientId?: string, name: string, path: string, };
