// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProtectionClassifierResult } from "./ProtectionClassifierResult";

export type WellbeingProtectionResult = { prompt: ProtectionClassifierResult, generation: ProtectionClassifierResult, };
