// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WindowsSandboxNuxPromptScreen } from "./WindowsSandboxNuxPromptScreen";
import type { WindowsSandboxNuxSurface } from "./WindowsSandboxNuxSurface";

export type WindowsSandboxNuxPromptParams = { surface: WindowsSandboxNuxSurface, screen: WindowsSandboxNuxPromptScreen, failureCode: string | null, failureMessage: string | null, };
