// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WindowsSandboxNuxSurface } from "./WindowsSandboxNuxSurface";
import type { WindowsSandboxSetupStatus } from "./WindowsSandboxSetupStatus";

export type WindowsSandboxSetupStatusNotification = { surface: WindowsSandboxNuxSurface, status: WindowsSandboxSetupStatus, attempt: number, elapsedMs: bigint, failureCode: string | null, failureMessage: string | null, };
