// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorktreeDirtyState } from "./WorktreeDirtyState";

/**
 * Dirty-state response returned by \`worktree/inspectSource\`.
 */
export type WorktreeInspectSourceResponse = { dirty: WorktreeDirtyState, };
