// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Remove stale managed worktree metadata from app-server storage.
 */
export type WorktreePruneParams = { dryRun?: boolean, };
