// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request the managed worktrees associated with the repository containing \`cwd\`.
 */
export type WorktreeListParams = {
/**
 * Repository-relative workspace cwd to inspect. Omitted uses app-server's effective cwd.
 */
cwd?: string | null,
/**
 * Include managed worktrees from every repository known to this app-server.
 */
all?: boolean, };
