// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorktreeInfo } from "./WorktreeInfo";

/**
 * Managed worktrees returned by \`worktree/list\`.
 */
export type WorktreeListResponse = { data: Array<WorktreeInfo>, };
