// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Remove a managed worktree in the repository containing \`cwd\`.
 */
export type WorktreeRemoveParams = {
/**
 * Repository-relative workspace cwd to use when resolving \`name_or_path\`.
 */
cwd?: string | null, nameOrPath: string, force?: boolean, deleteBranch?: boolean, };
