// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorktreeDirtyPolicy } from "./WorktreeDirtyPolicy";

/**
 * Create or reuse a managed worktree from the repository containing \`cwd\`.
 */
export type WorktreeCreateParams = {
/**
 * Repository-relative workspace cwd to use as the source checkout.
 */
cwd?: string | null, branch: string, baseRef?: string | null, dirtyPolicy: WorktreeDirtyPolicy, };
