// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorktreeInfo } from "./WorktreeInfo";
import type { WorktreeWarning } from "./WorktreeWarning";

/**
 * Result returned by \`worktree/create\`.
 */
export type WorktreeCreateResponse = { reused: boolean, info: WorktreeInfo, warnings: Array<WorktreeWarning>, };
