// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Inspect dirty state for the repository containing \`cwd\`.
 */
export type WorktreeInspectSourceParams = {
/**
 * Repository-relative workspace cwd to inspect. Omitted uses app-server's effective cwd.
 */
cwd?: string | null, };
