/*
 * codex-backend
 *
 * codex-backend
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupSpendControlLimitDetails {
    #[serde(rename = "group_id")]
    pub group_id: String,
    #[serde(rename = "group_name")]
    pub group_name: String,
    #[serde(rename = "details")]
    pub details: Box<models::SpendControlLimitDetails>,
}

impl GroupSpendControlLimitDetails {
    pub fn new(
        group_id: String,
        group_name: String,
        details: models::SpendControlLimitDetails,
    ) -> Self {
        Self {
            group_id,
            group_name,
            details: Box::new(details),
        }
    }
}
