/*
 * codex-backend
 *
 * codex-backend
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SpendControlLimitType {
    #[serde(rename = "individual")]
    Individual,
    #[serde(rename = "group_default")]
    GroupDefault,
    #[serde(rename = "workspace_default")]
    WorkspaceDefault,
    #[serde(rename = "role_budget")]
    RoleBudget,
    #[serde(rename = "group_shared")]
    GroupShared,
    #[serde(rename = "workspace_shared")]
    WorkspaceShared,
}

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpendControlStatusDetails {
    #[serde(rename = "reached")]
    pub reached: bool,
    #[serde(
        rename = "reached_limit_type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reached_limit_type: Option<Option<SpendControlLimitType>>,
    #[serde(
        rename = "individual_limit",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub individual_limit: Option<Option<Box<models::SpendControlLimitDetails>>>,
    #[serde(
        rename = "group_default_limit",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub group_default_limit: Option<Option<Box<models::GroupSpendControlLimitDetails>>>,
    #[serde(
        rename = "workspace_default_limit",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub workspace_default_limit: Option<Option<Box<models::SpendControlLimitDetails>>>,
    #[serde(
        rename = "role_budget_limit",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub role_budget_limit: Option<Option<Box<models::SpendControlLimitDetails>>>,
    #[serde(
        rename = "group_shared_limit",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub group_shared_limit: Option<Option<Box<models::GroupSpendControlLimitDetails>>>,
    #[serde(
        rename = "workspace_shared_limit",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub workspace_shared_limit: Option<Option<Box<models::SpendControlLimitDetails>>>,
}

impl SpendControlStatusDetails {
    pub fn new(reached: bool) -> Self {
        Self {
            reached,
            reached_limit_type: None,
            individual_limit: None,
            group_default_limit: None,
            workspace_default_limit: None,
            role_budget_limit: None,
            group_shared_limit: None,
            workspace_shared_limit: None,
        }
    }
}
