// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationErrorEvent } from "../../../../exec/bindings/ConversationErrorEvent";
import type { ItemCompletedEvent } from "../../../../exec/bindings/ItemCompletedEvent";
import type { ItemStartedEvent } from "../../../../exec/bindings/ItemStartedEvent";
import type { ItemUpdatedEvent } from "../../../../exec/bindings/ItemUpdatedEvent";
import type { SessionCreatedEvent } from "../../../../exec/bindings/SessionCreatedEvent";
import type { TurnCompletedEvent } from "../../../../exec/bindings/TurnCompletedEvent";
import type { TurnStartedEvent } from "../../../../exec/bindings/TurnStartedEvent";

/**
 * Top-level events emitted on the Codex Exec conversation stream.
 */
export type ConversationEvent = { "type": "session.created" } & SessionCreatedEvent | { "type": "turn.started" } & TurnStartedEvent | { "type": "turn.completed" } & TurnCompletedEvent | { "type": "item.started" } & ItemStartedEvent | { "type": "item.updated" } & ItemUpdatedEvent | { "type": "item.completed" } & ItemCompletedEvent | { "type": "error" } & ConversationErrorEvent;
