from __future__ import annotations

from typing import Any, NotRequired, TypedDict

# Generated by scripts/generate_protocol_typed_dicts.py

class ThreadObject(TypedDict):
    cliVersion: str
    createdAt: int
    cwd: str
    gitInfo: NotRequired[dict[str, Any]]
    id: str
    modelProvider: str
    path: NotRequired[str | None]
    preview: str
    source: dict[str, Any]
    turns: list[dict[str, Any]]
    updatedAt: int

class TurnObject(TypedDict):
    error: NotRequired[dict[str, Any]]
    id: str
    items: list[dict[str, Any]]
    status: dict[str, Any]

class ThreadStartResponse(TypedDict):
    approvalPolicy: dict[str, Any]
    cwd: str
    model: str
    modelProvider: str
    reasoningEffort: NotRequired[dict[str, Any]]
    sandbox: dict[str, Any]
    thread: ThreadObject

class ThreadResumeResponse(TypedDict):
    approvalPolicy: dict[str, Any]
    cwd: str
    model: str
    modelProvider: str
    reasoningEffort: NotRequired[dict[str, Any]]
    sandbox: dict[str, Any]
    thread: ThreadObject

class ThreadListResponse(TypedDict):
    data: list[dict[str, Any]]
    nextCursor: NotRequired[str | None]

class ThreadReadResponse(TypedDict):
    thread: ThreadObject

class TurnStartResponse(TypedDict):
    turn: TurnObject

class TurnCompletedNotificationParams(TypedDict):
    threadId: str
    turn: TurnObject
