mod background;
mod context;
mod definition;
pub mod definitions;
mod filter;
mod manager;
pub mod signal;
mod spawn;
mod transcript;

pub use background::BackgroundAgent;
pub use context::ChildToolUseContext;
pub use definition::AgentDefinition;
pub use definitions::builtin_agents;
pub use definitions::builtin_agents_with_config;
pub use definitions::builtin_agents_with_overrides;
pub use filter::filter_tools_for_agent;
pub use manager::AgentExecuteFn;
pub use manager::AgentInstance;
pub use manager::AgentStatus;
pub use manager::SpawnResult;
pub use manager::SubagentManager;
pub use signal::backgroundable_agent_ids;
pub use signal::is_agent_backgroundable;
pub use signal::register_backgroundable_agent;
pub use signal::trigger_background_transition;
pub use signal::unregister_backgroundable_agent;
pub use spawn::SpawnInput;
pub use transcript::TranscriptRecorder;
