#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${repo_root}"

# Bazel wildcard builds skip manual targets, which misses the internal
# `*-unit-tests-bin` rust_test targets generated by `codex_rust_crate()`.
# Add only those manual rust_test targets explicitly so inline `#[cfg(test)]`
# call sites are linted without pulling in unrelated manual release targets.
query='kind("rust_test rule", attr(tags, "manual", //codex-rs/...))'
if [[ "${GITHUB_ACTIONS:-}" == "true" ]]; then
  manual_rust_test_targets="$(
    ./.github/scripts/run-bazel-query-ci.sh \
      --output=label \
      -- "${query}"
  )"
else
  manual_rust_test_targets="$(bazel query --output=label "${query}")"
fi
if [[ "${RUNNER_OS:-}" != "Windows" ]]; then
  manual_rust_test_targets="$(printf '%s\n' "${manual_rust_test_targets}" | grep -v -- '-windows-cross-bin$' || true)"
fi

printf '%s\n' "//codex-rs/..."
printf '%s\n' "${manual_rust_test_targets}"
