#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${repo_root}"

# Bazel wildcard builds skip manual targets, which misses the internal
# `*-unit-tests-bin` rust_test targets generated by `codex_rust_crate()`.
# Add only those manual rust_test targets explicitly so inline `#[cfg(test)]`
# call sites are linted without pulling in unrelated manual release targets.
manual_rust_test_targets="$(
  ./.github/scripts/run-bazel-query-ci.sh \
    --output=label \
    -- 'kind("rust_test rule", attr(tags, "manual", //codex-rs/...))'
)"
if [[ "${RUNNER_OS:-}" != "Windows" ]]; then
  manual_rust_test_targets="$(printf '%s\n' "${manual_rust_test_targets}" | grep -v -- '-windows-cross-bin$' || true)"
fi

# Generated `*-wine-exec-test` targets are Linux launchers around the host-native test binary and
# a separately transitioned Windows exec-server binary. The corresponding native test target is
# linted on Linux and macOS, while the exec-server binary is linted under `cfg(windows)` by the
# Windows lint job. Exclude only the launchers here because this lint configuration cannot analyze
# their transitioned data dependency.
wine_exec_test_targets="$(
  ./.github/scripts/run-bazel-query-ci.sh \
    --output=label \
    -- 'filter(".*-wine-exec-test$", //codex-rs/...)'
)"

printf '%s\n' \
  "//codex-rs/..." \
  "-//codex-rs/core/tests/remote_env_windows:smoke-test"
printf '%s\n' "${wine_exec_test_targets}" | sed 's#^#-#'
printf '%s\n' "${manual_rust_test_targets}"
