// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A UTF-8 path rendered using an explicitly selected native path convention.
 *
 * "Native" refers to the supplied [`PathConvention`], which may be foreign to
 * the operating system running this process. The inner string is private so
 * path-producing code must render through [`Self::from_path_uri`] rather than
 * accidentally applying the current host's path rules. Opaque fallback paths
 * are decoded using the supplied convention and converted to UTF-8 lossily at
 * this API boundary because the value is serialized as a JSON string.
 */
export type ApiPathString = string;
