// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadId } from "./ThreadId";

export type ArchiveConversationParams = { conversationId: ThreadId, 
/**
 * Optional legacy parameter: newer clients may omit or send null and rely
 * on the server to resolve the rollout path from the conversation id.
 */
rolloutPath: string | null, };
