// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AskUserQuestionOption } from "./AskUserQuestionOption";
import type { AskUserQuestionType } from "./AskUserQuestionType";

export type AskUserQuestion = { id: string, prompt: string, type: AskUserQuestionType, description?: string, placeholder?: string, options?: Array<AskUserQuestionOption>, allowOther?: boolean, required?: boolean, };
