// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AskUserQuestion } from "./AskUserQuestion";

export type AskUserQuestionRequest = { title?: string, questions: Array<AskUserQuestion>, };
