// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Authentication modes reported by the deprecated v1 auth-status API.
 *
 * Personal access tokens intentionally report `Chatgpt` to preserve the v1 wire contract.
 */
export type AuthMode = "apikey" | "chatgpt" | "chatgptAuthTokens" | "agentIdentity";
