// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Workspace IDs that ChatGPT auth is allowed to use.
 *
 * The config parser accepts the historical single-string form and the newer
 * list form for deployments that allow multiple ChatGPT workspaces.
 */
export type ForcedChatgptWorkspaceIds = string | Array<string>;
