// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientInfo } from "./ClientInfo";
import type { InitializeCapabilities } from "./InitializeCapabilities";
import type { McpClientCapabilities } from "./McpClientCapabilities";

export type InitializeParams = { clientInfo: ClientInfo, capabilities: InitializeCapabilities | null,
/**
 * MCP client capabilities that app-server may advertise to downstream MCP servers.
 */
mcpClientCapabilities?: McpClientCapabilities | null, };
