// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalShellAction } from "./LocalShellAction";
import type { LocalShellStatus } from "./LocalShellStatus";

export type LocalShellCall = { 
/**
 * Set when using the Responses API.
 */
call_id: string | null, status: LocalShellStatus, action: LocalShellAction, };
