// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Passive MCP App presentation features supported by the active host.
 */
export type McpAppUiCapability = "webView" | "declarativeUi";
