// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpAppUiCapability } from "./McpAppUiCapability";

/**
 * Passive MCP capabilities supplied by the active Codex host.
 */
export type McpClientCapabilities = { appUi: Array<McpAppUiCapability>, };
