// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls the effective multi-agent delegation instructions for a turn. `none` bypasses the
 * built-in explicit/proactive policy so configured mode instructions can define the policy.
 */
export type MultiAgentMode = "none" | "explicitRequestOnly" | "proactive";
