// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestUserInputQuestion } from "./RequestUserInputQuestion";
import type { JsonValue } from "./serde_json/JsonValue";

export type RequestUserInputEvent = { 
/**
 * Responses API call id for the associated tool call, if available.
 */
call_id: string, 
/**
 * Turn ID that this request belongs to.
 * Uses `#[serde(default)]` for backwards compatibility.
 */
turn_id: string, tool: string | null, arguments: JsonValue | null, questions: Array<RequestUserInputQuestion>, };
