// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Compaction } from "./Compaction";
import type { CustomToolCall } from "./CustomToolCall";
import type { CustomToolCallOutput } from "./CustomToolCallOutput";
import type { FunctionCall } from "./FunctionCall";
import type { FunctionCallOutput } from "./FunctionCallOutput";
import type { GhostSnapshot } from "./GhostSnapshot";
import type { LocalShellCall } from "./LocalShellCall";
import type { Message } from "./Message";
import type { Reasoning } from "./Reasoning";
import type { WebSearchCall } from "./WebSearchCall";

export type ResponseItem = { "type": "message" } & Message | { "type": "reasoning" } & Reasoning | { "type": "local_shell_call" } & LocalShellCall | { "type": "function_call" } & FunctionCall | { "type": "function_call_output" } & FunctionCallOutput | { "type": "custom_tool_call" } & CustomToolCall | { "type": "custom_tool_call_output" } & CustomToolCallOutput | { "type": "web_search_call" } & WebSearchCall | { "type": "ghost_snapshot" } & GhostSnapshot | { "type": "compaction" } & Compaction | { "type": "other" };
