// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls latency/cost class for OpenAI Responses API requests.
 * Serialized with lowercase values to match the OpenAI API.
 */
export type ServiceTier = "auto" | "default" | "flex";
