// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelVisibleState } from "./ModelVisibleState";

export type ThreadRolledBackEvent = { 
/**
 * Number of user turns that were removed from context.
 */
num_turns: number, 
/**
 * Model-visible session state after rollback.
 *
 * This lets clients synchronize UI mode/model indicators with core after history rewind.
 * Optional for backward compatibility with older persisted events.
 */
model_visible_state?: ModelVisibleState, };
