// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCallType } from "./ToolCallType";

/**
 * CRAFT AGENTS: Event requesting PreToolUse hook decision.
 * Sent to client BEFORE any tool execution to allow interception.
 */
export type ToolCallPreExecuteRequestEvent = { 
/**
 * Identifier for the tool call.
 */
callId: string, 
/**
 * Turn ID that this tool call belongs to.
 */
turnId: string, 
/**
 * The type of tool being executed.
 */
toolType: ToolCallType, 
/**
 * The name of the tool (e.g., "bash", "mcp__github__create_issue").
 */
toolName: string, 
/**
 * The tool input as JSON string.
 */
input: string, 
/**
 * For MCP tools: the server name.
 */
mcpServer: string | null, 
/**
 * For MCP tools: the actual tool name within the server.
 */
mcpTool: string | null, };
