// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebSearchContextSize } from "./WebSearchContextSize";
import type { WebSearchFilters } from "./WebSearchFilters";
import type { WebSearchUserLocation } from "./WebSearchUserLocation";

export type WebSearchConfig = { filters: WebSearchFilters | null, user_location: WebSearchUserLocation | null, search_context_size: WebSearchContextSize | null, };
