// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "./AbsolutePathBuf";

/**
 * Controls read access semantics for `workspace-write` sandbox policies.
 */
export type WorkspaceReadAccess = { "type": "full-read-access" } | { "type": "restricted-read-access", 
/**
 * Additional folders that should be readable from inside the sandbox.
 */
readable_roots?: Array<AbsolutePathBuf>, };
