set positional-arguments

# Display help
help:
    just -l

# `codex-custom`
codex *args:
    cargo run --bin codex-custom -- "$@"

# `codex exec`
exec *args:
    cargo run --bin codex-custom -- exec "$@"

# `codex tui`
tui *args:
    cargo run --bin codex-tui -- "$@"

# Run the CLI version of the file-search crate.
file-search *args:
    cargo run --bin codex-file-search -- "$@"

# format code
fmt:
    cargo fmt -- --config imports_granularity=Item

fix:
    cargo clippy --fix --all-features --tests --allow-dirty

install:
    rustup show active-toolchain
    cargo fetch
