name: Review Gate

on:
  workflow_dispatch: {}
  issue_comment:
    types: [created]
  workflow_run:
    workflows: ["CI", "Build", "Tests", "Format / etc", "build-test"]
    types: [completed]

permissions:
  contents: read
  pull-requests: read
  issues: write

jobs:
  gate:
    if: |
      github.event_name != 'workflow_run' && (github.ref_name == 'main' || github.ref_name == 'feat/agent-bus') ||
      (github.event_name == 'workflow_run' && (github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'feat/agent-bus'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: cli/gh-action@v2
      - name: Run review_gate
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPSTREAM_GH_TOKEN: ${{ secrets.UPSTREAM_GH_TOKEN }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: |
          python3 scripts/review_gate.py

