name: sdk

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  typescript-sdk:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: pnpm

      - uses: dtolnay/rust-toolchain@1.90

      - name: build codex
        run: cargo build --bin codex
        working-directory: codex-rs

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build SDK packages
        run: pnpm -r --filter ./sdk/typescript run build

      - name: Lint SDK packages
        run: pnpm -r --filter ./sdk/typescript run lint

      - name: Test SDK packages
        run: pnpm -r --filter ./sdk/typescript run test

  python-sdk:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@1.90

      - name: Build codex
        run: cargo build --bin codex
        working-directory: codex-rs

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
          enable-cache: true
          cache-dependency-glob: |
            sdk/python/pyproject.toml
            sdk/python/uv.lock

      - name: Install Python runtime
        run: uv python install 3.12

      - name: Sync Python dependencies
        run: uv sync --project sdk/python --extra dev

      - name: Lint Python SDK
        run: uv run --project sdk/python ruff check

      - name: Type-check Python SDK
        run: uv run --project sdk/python mypy --config-file sdk/python/pyproject.toml sdk/python/src/codex

      - name: Test Python SDK
        run: uv run --project sdk/python pytest
